### ISSUE TITLE
Error: Could not parse CSS stylesheet - Media print format

### ISSUE THREAD

**Issue by Geminii** [jsdom/jsdom#2641]
### Basic info:

- **Node.js version:** latest
- **jsdom version:** latest

### Minimal reproduction case

```bash
    type: 'css parsing',
    message: 'Could not parse CSS stylesheet'
```

Simply easy to reproduce : 
```css
@media print {
  @page {
      size: A4;
   }
}
```

Could be pretty cool to accept this valid css rules format :) 
To fix this, i just change the `size: 210mm 297mm;` 

Thanks a lot for your work :)

**Comment by Geminii** [comment]
My apologize. It was due to my imbrication in sass. 
For some understood reason, this code generate a problem at Jsdom to parse : 
```css
@media print {
  @page {
    size: A4;
    
    &:first {
        margin: 0 50px;
     }
  }
}
```

Solution is to do this : 
```css
@media print {
  @page {
    size: A4;
  }

  @page :first {
    margin: 0 50px;
  }
}
```
