### ISSUE TITLE
`getComputedStyle()` ignores specificity priority

### ISSUE THREAD

**Issue by danon** [jsdom/jsdom#3318]
### Basic info:

- **Node.js version:** 16.13.0
- **jsdom version:** 19.0.0

1. Use any styles, that depend on specificy
   ```css
   <style>
    .parent p { color: black; }  // this should take precedense, since it's more specific, according to CSS
    p { color: red; }
   </style>
   ```
2. Use them in HTML

The CSS specificity rules are described: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

### Minimal reproduction case

```js
var JSDOM = require("jsdom").JSDOM;

const dom = new JSDOM(`<!DOCTYPE html>
<style>
 div.parent p { color: black; }
 p { color: red; }
</style>

<div class="parent">
    <p>Hi</p>
</div>
`);

const style = dom.window.getComputedStyle(dom.window.document.querySelector("p"));

console.log(style);

```

### How does similar code behave in browsers?

In every browser, `getComputedStyle()` returns `color: black`, in JSDOM it's `color: red`.

![image](https://user-images.githubusercontent.com/13367735/149621483-a63f4730-1779-409b-ab4d-48be33aaf4eb.png)
![image](https://user-images.githubusercontent.com/13367735/149621510-628a5909-bc7a-4e3f-a58a-e0f7729f1f30.png)
![image](https://user-images.githubusercontent.com/13367735/149621526-696dea3a-1633-4d87-a035-cfaf6c127f1b.png)
